AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: smart sheet proxy server.

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        Me:
          Type: Api
          Properties:
            Path: /2.0/users/me
            Method: get
        Sheets:
          Type: Api
          Properties:
            Path: /2.0/sheets
            Method: get
        Sheet:
          Type: Api
          Properties:
            Path: /2.0/sheets/{sheetId}
            Method: get